### ISSUE TITLE
colonists waste all of ammo with combat extended

### ISSUE THREAD

**Issue by QuakeIV** [pardeike/Zombieland#24] opened 2020-01-02 23:03 UTC
To start, as far as I can tell this claims to be CE compatible.

For some reason when I'm trying to play with combat extended, whenever a colonist with a gun gets within range of a zombie (even if un-drafted) they will start firing at the maximum possible range, even with like 500 trees in the way, and will burn up all of their ammo.  This is particularly bad on a new colony because of two reasons.

A. They run out of very limited starting ammo very fast.
B. This attracts all of the zombies, meaning the ammo runs out even faster

Please advise because this is making it kindof impractical to play with both.

**Comment by pardeike** [comment] 2020-01-03 08:00
This is the normal auto attack response from Vanilla. Has nothing to do with CE or Zombieland. Controlled by the little icon in the pawn inspector (Flee, Ignore, Attack).

**Comment by QuakeIV** [comment] 2020-01-03 21:08
I also have a confirmed instance of them trying to shoot at zombies outside of a cave from inside a cave.  I can confirm its outside of the normal behaviour insofar as they seem to have no ability to determine if they really have a shot or not, unlike normal targets.

**Comment by QuakeIV** [comment] 2020-01-03 22:15
The colony in question died but I can put together a new one to test the true weirdness of the line of sight issues if you like.

**Comment by pardeike** [comment] 2020-01-04 04:21
I’ve heard about a mod conflict before where colonists aim and shoot even through walls. This sounds similar but I am not sure how I would fix this. To me this bug clearly lands in CE territory and should be reported and fixed there. 

Unless someone can clearly show that this is caused by ZL it is most likely a WONTFIX

**Comment by QuakeIV** [comment] 2020-01-04 04:23
I was talking to the CE guy and he seems to think it has to do with some kind of simplified LOS system that was put in place to help the hordes of zombies work better.  He wasn't actually sure which mod contained the code for that.

**Comment by pardeike** [comment] 2020-01-04 04:40
Zombieland itself has some patches to the existing vanilla code to prioritise different zombies (do crawling zombies last) and other minor stuff. But this all works with normal vanilla and thus includes normal LOS. While the zombie logic is very custom I tried to keep the basic interactions very much vanilla to not cause any problems. 

I think it might be another mod that messes with the issue and last time I tested CE and ZL (fixing some armour issues) I did not notice any aiming problems. Are you seeing the issue with CE and ZL only or are other mods involved too?

**Comment by QuakeIV** [comment] 2020-01-04 05:56
I loaded just three mods for a quick test: Zombieland, Combat Extended, and a tree density increasing mod.  I was able to recreate the excessive engagement range, and also a less extreme but still impossible shot (where the colonist actually went so far as firing into the wall after I unpaused from this screenshot):

https://i.imgur.com/sI6IZhG.png

The shooter was also momentarily aiming at other targets, including some zombies to her north, which she did not go so far as to fire on:

https://i.imgur.com/z6gAE5d.png

I think this more or less qualifies as a recreation of the scenario.  I attached the save file (renamed to .txt so github would accept it, it was originally .rws).

[New Arrivals67.txt](https://github.com/pardeike/Zombieland/files/4021584/New.Arrivals67.txt)

Here is my mod list:
https://i.imgur.com/qhIsSJQ.png

The dense biomes was installed so I could recreate the excessive engagement range scenario where they would fire long distance through many many trees.

**Comment by pardeike** [comment] 2020-01-04 12:56
Thanks to the perfect save file I could narrow down the problem to be in fact in Zombieland. The main problem was that my understanding was that verb.CanHitTargetFrom() included LOS calculations but it does not. By adding an extra check with attacker.CanSee() to my code that makes friendlies be more smart about shooting zombies it fixes the issue.

I will package this fix together with another enhancement into the next release which will be v1.17.

Thanks!

**Closed as completed by pardeike** 2020-01-04 12:56 UTC

**Comment by QuakeIV** [comment] 2020-01-04 19:23
Ayyyyyyyyyy glad to be of assistance

**Comment by pardeike** [comment] 2020-01-04 19:49
Please verify with latest release. Thank you.

**Comment by QuakeIV** [comment] 2020-01-06 04:43
The excessive engagement range thing still comes up on occasion (shooting through many trees) however the fact that they no longer fire into obstacles greatly improves the situation, so assuming the tree thing isn't something you are inclined to fix I would say this is indeed resolved.
